# Generated by Django 2.0.3 on 2018-03-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_subject', models.CharField(max_length=255, verbose_name='文档标题')),
                ('doc_body', models.TextField(max_length=2550, verbose_name='文档正文')),
                ('doc_ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('doc_utime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文档管理',
                'verbose_name_plural': '文档管理',
            },
        ),
    ]
