# Generated by Django 2.0.3 on 2018-03-23 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name': '文档管理', 'verbose_name_plural': '文档管理'},
        ),
    ]
