# Generated by Django 2.0.3 on 2018-03-29 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_status', models.CharField(choices=[('runing', '在用'), ('stop', '停用')], default='runing', max_length=100, verbose_name='资产状态')),
                ('assets_type', models.CharField(choices=[('server', '服务器'), ('vmser', '虚拟机'), ('switch', '交换机')], default='server', max_length=100, verbose_name='资产类型')),
                ('assets_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='主机的用途')),
                ('hostname', models.CharField(blank=True, max_length=64, null=True, verbose_name='资产名称')),
                ('network_ip', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('manage_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='型号')),
                ('system', models.CharField(blank=True, max_length=128, null=True, verbose_name='系统版本')),
                ('pro_name', models.CharField(blank=True, default='', max_length=64, verbose_name='项目名')),
                ('cabinet', models.CharField(blank=True, default='', max_length=64, verbose_name='机柜')),
                ('position', models.CharField(blank=True, default='', max_length=64, verbose_name='位置')),
                ('user_name', models.CharField(blank=True, default='', max_length=32, verbose_name='登录用户名')),
                ('pass_word', models.CharField(blank=True, default='', max_length=64, verbose_name='登录密码')),
                ('sn', models.CharField(blank=True, max_length=64, verbose_name='序列号')),
                ('cpu', models.CharField(blank=True, default='', max_length=64, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, default=8, max_length=64, verbose_name='内存')),
                ('disk', models.CharField(blank=True, default=300, max_length=256, verbose_name='硬盘')),
                ('ps', models.TextField(blank=True, default='', max_length=1024, verbose_name='备注')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '资产管理',
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='data_centers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_center_list', models.CharField(max_length=128, null=True, verbose_name='数据中心')),
            ],
            options={
                'verbose_name': '数据中心',
                'verbose_name_plural': '数据中心',
                'db_table': 'data_centers',
            },
        ),
        migrations.CreateModel(
            name='PortMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_port', models.GenericIPAddressField(unique=True, verbose_name='内网端口')),
                ('out_ip', models.GenericIPAddressField(verbose_name='外网IP')),
                ('out_port', models.SmallIntegerField(verbose_name='外网端口')),
                ('ask_user', models.CharField(max_length=32, verbose_name='申请人')),
                ('use_for', models.CharField(max_length=128, verbose_name='用途')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('stop_time', models.DateField(verbose_name='结束时间')),
                ('ps', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('in_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.assets', verbose_name='内网IP')),
            ],
            options={
                'verbose_name': '端口映射表',
                'verbose_name_plural': '端口映射表',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Country'),
        ),
        migrations.AddField(
            model_name='assets',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.City', verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='assets',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Country', verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='assets',
            name='data_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.data_centers', verbose_name='数据中心'),
        ),
    ]
