# Generated by Django 2.0.3 on 2018-03-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_status', models.CharField(choices=[('runing', '在用'), ('stop', '停用')], default='runing', max_length=100, verbose_name='资产状态')),
                ('assets_type', models.CharField(choices=[('server', '服务器'), ('vmser', '虚拟机'), ('switch', '交换机')], default='server', max_length=100, verbose_name='资产类型')),
                ('assets_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='主机的用途')),
                ('hostname', models.CharField(blank=True, max_length=64, null=True, verbose_name='资产名称')),
                ('network_ip', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('manage_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='型号')),
                ('system', models.CharField(blank=True, max_length=128, null=True, verbose_name='系统版本')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='序列号')),
                ('cpu', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=64, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=256, null=True, verbose_name='硬盘')),
                ('ps', models.TextField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '资产管理',
                'db_table': 'asset',
            },
        ),
    ]
