# Generated by Django 2.0.3 on 2018-03-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='assets_status',
            field=models.CharField(choices=[('在用', '在用'), ('停用', '停用')], default='runing', max_length=100, verbose_name='资产状态'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_type',
            field=models.CharField(choices=[('服务器', '服务器'), ('虚拟机', '虚拟机'), ('交换机', '交换机')], default='server', max_length=100, verbose_name='资产类型'),
        ),
    ]
