# Generated by Django 2.0.3 on 2018-03-29 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portmap',
            name='in_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portmaps', to='assets.assets', verbose_name='内网IP'),
        ),
        migrations.AlterField(
            model_name='portmap',
            name='in_port',
            field=models.SmallIntegerField(verbose_name='内网端口'),
        ),
    ]
