# Generated by Django 2.0.3 on 2018-04-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180329_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portmap',
            name='in_ip',
            field=models.GenericIPAddressField(verbose_name='内网IP'),
        ),
    ]
