# Generated by Django 2.0.3 on 2018-03-23 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180323_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_centers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_center_list', models.CharField(max_length=128, null=True, verbose_name='数据中心')),
            ],
            options={
                'verbose_name': '数据中心',
                'verbose_name_plural': '数据中心',
                'db_table': 'data_centers',
            },
        ),
        migrations.AddField(
            model_name='assets',
            name='cabinet',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='机柜'),
        ),
        migrations.AddField(
            model_name='assets',
            name='pass_word',
            field=models.CharField(default='', max_length=64, verbose_name='登录密码'),
        ),
        migrations.AddField(
            model_name='assets',
            name='position',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='位置'),
        ),
        migrations.AddField(
            model_name='assets',
            name='pro_name',
            field=models.CharField(default='', max_length=64, verbose_name='项目名'),
        ),
        migrations.AddField(
            model_name='assets',
            name='user_name',
            field=models.CharField(default='', max_length=32, verbose_name='登录用户名'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_status',
            field=models.CharField(choices=[('runing', '在用'), ('stop', '停用')], default='runing', max_length=100, verbose_name='资产状态'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_type',
            field=models.CharField(choices=[('server', '服务器'), ('vmser', '虚拟机'), ('switch', '交换机')], default='server', max_length=100, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='disk',
            field=models.CharField(blank=True, default=300, max_length=256, null=True, verbose_name='硬盘'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='memory',
            field=models.CharField(blank=True, default=8, max_length=64, null=True, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='network_ip',
            field=models.GenericIPAddressField(verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='assets',
            name='data_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.data_centers', verbose_name='数据中心'),
        ),
    ]
