# Generated by Django 2.0.3 on 2018-03-26 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180323_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='assets',
            name='cabinet',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='机柜'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='cpu',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='disk',
            field=models.CharField(blank=True, default=300, max_length=256, verbose_name='硬盘'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='memory',
            field=models.CharField(blank=True, default=8, max_length=64, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='pass_word',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='登录密码'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='position',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='pro_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='ps',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='sn',
            field=models.CharField(blank=True, default=1, max_length=64, verbose_name='序列号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assets',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='登录用户名'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Country'),
        ),
        migrations.AddField(
            model_name='assets',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.City'),
        ),
        migrations.AddField(
            model_name='assets',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Country'),
        ),
    ]
