# Generated by Django 2.0.3 on 2018-03-29 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180326_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_ip', models.GenericIPAddressField(verbose_name='外网IP')),
                ('out_port', models.SmallIntegerField(verbose_name='外网端口')),
                ('in_ip', models.GenericIPAddressField(verbose_name='内网IP')),
                ('in_port', models.SmallIntegerField(verbose_name='内网端口')),
                ('ask_user', models.CharField(max_length=32, verbose_name='申请人')),
                ('use_for', models.CharField(max_length=128, verbose_name='用途')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('stop_time', models.DateField(verbose_name='结束时间')),
                ('ps', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '端口映射表',
                'verbose_name_plural': '端口映射表',
            },
        ),
        migrations.AlterField(
            model_name='assets',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.City', verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Country', verbose_name='国家'),
        ),
    ]
